name: Setup & install
description: install pnpm & deps

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 9

    - uses: actions/setup-node@v4
      with:
        node-version: "20"
        cache: "pnpm"
        cache-dependency-path: "./pnpm-lock.yaml"

    - run: pnpm install
      shell: bash
