name: CIFD Test

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  actions: read
  checks: write

defaults:
  run:
    shell: bash

env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: lint, types, unit-tests
        run: pnpm test:ci

      - name: Unit-test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Unit-test Report
          path: reports/vitest.xml
          reporter: jest-junit

      - uses: codecov/codecov-action@v3
        if: ${{ github.ref_name == 'master' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          fail_ci_if_error: true
          verbose: true

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - run: pnpm cypress install

      - run: pnpm build

      - run: pnpm e2e:ci

      - name: E2E Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: E2E Report
          path: cypress/results/results-*.xml
          reporter: java-junit
