name: CIFD Test

on:
  push:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  actions: read
  checks: write

defaults:
  run:
    shell: bash

env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: "16.17"
          cache: "pnpm"
          cache-dependency-path: "./pnpm-lock.yaml"

      - run: pnpm install
      #--frozen-lockfile

      - name: test
        run: pnpm test:ci

      - name: build
        run: pnpm build

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Mocha Tests
          path: reports/mocha.json
          reporter: mocha-json
